"""Utilities for the AIDA Challenge Streamlit Application."""

from .data_loader import (
    get_db_connection,
    load_customer_demographics,
    load_policy_data,
    load_interaction_data,
    load_geographic_data,
    load_cluster_summary,
    load_channel_performance,
    load_product_performance,
    load_interaction_summary,
    load_cached_pitches,
    load_raw_clienti,
    load_raw_polizze,
    load_raw_sinistri,
    load_raw_reclami,
    load_raw_abitazioni,
    load_raw_interazioni_clienti,
    load_raw_competitor_prodotti,
    get_customer_list,
    get_customer_full_profile,
    get_nba_recommendations,
)

__all__ = [
    "get_db_connection",
    "load_customer_demographics",
    "load_policy_data",
    "load_interaction_data",
    "load_geographic_data",
    "load_cluster_summary",
    "load_channel_performance",
    "load_product_performance",
    "load_interaction_summary",
    "load_cached_pitches",
    "load_raw_clienti",
    "load_raw_polizze",
    "load_raw_sinistri",
    "load_raw_reclami",
    "load_raw_abitazioni",
    "load_raw_interazioni_clienti",
    "load_raw_competitor_prodotti",
    "get_customer_list",
    "get_customer_full_profile",
    "get_nba_recommendations",
]
